// <auto-generated />
namespace WebApplication2LeaveAndOverTimeReqestToolHasLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_last_edit_acc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_last_edit_acc));
        
        string IMigrationMetadata.Id
        {
            get { return "202001160357415_add_last_edit_acc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
